import { FieldState } from "../types/types";
import { gray } from "./colors";

export const initialFieldState: FieldState = {
    tetromino: undefined,
    gameOver: false,
    blockState: [
        [
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray }
        ],
        [
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray }
        ],
        [
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray }
        ],
        [
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray }
        ],
        [
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray }
        ],
        [
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray }
        ],
        [
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray }
        ],
        [
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray }
        ],
        [
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray }
        ],
        [
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray }
        ],
        [
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray }
        ],
        [
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray }
        ],
        [
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray }
        ],
        [
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray }
        ],
        [
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray }
        ],
        [
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray }
        ],
        [
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray }
        ],
        [
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray }
        ],
        [
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray }
        ],
        [
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray }
        ],
        [
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray }
        ],
        [
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray }
        ],
        [
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray }
        ],
        [
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray },
            { active: false, color: gray }
        ]
    ]
};